# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Install packit-service dependencies
  hosts: all
  vars:
    oc_download_link: https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/stable/openshift-client-linux.tar.gz
  tasks:
    - name: Enable EPEL repositories
      ansible.builtin.package:
        name:
          - epel-release
    - name: Install packages for deployment
      ansible.builtin.package:
        name:
          - ansible
          - python3-openshift
          - python3-pip
          - python3-passlib # for using htpasswd ansible module
          - make
          - podman

    #- name: Download OC
    #  ansible.builtin.get_url:
    #    url: "{{ oc_download_link }}"
    #    dest: /tmp
    #    mode: "0644"
    #  register: download
    #- name: Unarchive tarball in /usr/bin
    #  ansible.builtin.unarchive:
    #    src: "{{ download.dest }}"
    #    dest: /usr/bin
    #    list_files: True
    #    remote_src: True
