---
- name: Start Openshift Local cluster
  hosts: all
  become: true
  become_user: tmt
  gather_facts: False
  vars:
    pull_secret: "!!!TAKEN FROM ANSIBLE ENV!!!"
    dest_pull_secret_file: /tmp/openshift-local-pull-secret.txt
    crc_path: /home/tmt/.local/bin
  tasks:
    - name: Show pull secret
      ansible.builtin.debug:
        msg: "{{ pull_secret }}"
    - name: Create secret file from pull request var
      ansible.builtin.copy:
        content: "{{ pull_secret }}"
        dest: "{{ dest_pull_secret_file }}"
        mode: "0640"
        owner: tmt

    - name: Find user uid
      ansible.builtin.command: "id -u tmt"
      register: user_uid
      changed_when: false

    - name: Determine XDG_RUNTIME_DIR
      ansible.builtin.set_fact:
        xdg_runtime_dir: "/run/user/{{ user_uid.stdout }}"
      changed_when: false

    - name: Start cluster
      ansible.builtin.command: "{{ crc_path }}/crc start -c 6 -m 12000 -p {{ dest_pull_secret_file }}"
      #ansible.builtin.command: "crc start -p {{ dest_pull_secret_file }}"
      changed_when: False

    - name: Create symbolic link to oc
      ansible.builtin.file:
        #    src: "/tmp/{{ unarchive.files[0] }}/crc"
        src: /home/tmt/.crc/bin/oc/oc
        #    dest: "{{ crc_path }}/crc"
        dest: /home/tmt/.local/bin/oc
        state: link
        force: True
