---
- name: Configure a user able to run a Openshift Local Cluster
  hosts: all
  tasks:
    - name: Add tmt user
      ansible.builtin.user:
        name: tmt
        append: true
        groups: wheel
    - name: Add tmt user to sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        #line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
        line: "tmt ALL=(ALL) NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s
    - name: Enable lingering for tmt
      ansible.builtin.command: loginctl enable-linger tmt
      changed_when: False
