---
- name: Start Openshift Local cluster
  hosts: all
  gather_facts: False
  vars:
    pull_secret: "!!!TAKEN FROM VAGRANT FILE!!!"
    dest_pull_secret_file: /tmp/openshift-local-pull-secret.txt
  tasks:
    - name: Show pull secret
      ansible.builtin.debug:
        msg: "{{ pull_secret }}"
    - name: Create secret file from pull request var
      ansible.builtin.copy:
        content: "{{ pull_secret }}"
        dest: "{{ dest_pull_secret_file }}"
        mode: "0640"
    - name: Start cluster
      ansible.builtin.command: crc start -p {{ dest_pull_secret_file }}
      changed_when: False
