name: Schedule test on Testing Farm
on:
  issue_comment:
    types:
      - created

# The concurrency key is used to prevent multiple workflows from running at the same time
concurrency:
  group: my-concurrency-group
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request
      && contains(github.event.comment.body, '[test]')
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
      - name: Schedule test on Testing Farm
        uses: sclorg/testing-farm-as-github-action@v2
        with:
          api_key: ${{ secrets.TF_API_KEY }}
          git_url: "https://github.com/majamassarini/deployment"
          git_ref: "tf-openshift-tests"
          tmt_plan_regex: "deployment"
          pull_request_status_name: "Deployment"
          create_issue_comment: true
          timeout: 3600
          secrets: CRC_PULL_SECRET=${{ secrets.CRC_PULL_SECRET }}
